USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE LOGISTICS_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE LOGISTICS_DB.GOLD.route_performance
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@LOGISTICS_DB.GOLD.logistics_gold_stage/route_performance/',
      FILE_FORMAT => 'PARQUET_FF'
    )
  )
);

COPY INTO LOGISTICS_DB.GOLD.route_performance
FROM @LOGISTICS_DB.GOLD.logistics_gold_stage/route_performance/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet';
